set_property SRC_FILE_INFO {cfile:/home/esteban/Escritorio/pProyect_digt_2/MP3/mp3/mp3.srcs/constrs_1/new/Nexys_Master.xdc rfile:../../../mp3.srcs/constrs_1/new/Nexys_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property src_info {type:XDC file:1 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T16 [get_ports pasar1]
set_property src_info {type:XDC file:1 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H4 [get_ports {salida1}]
